#!/usr/bin/env bash
# gen-memory-digest.sh - build the always-load AI-Memory digest.
#
# USAGE
#   bash _scripts/gen-memory-digest.sh [VAULT_ROOT]
#
# OUTPUT
#   Engineering/AI-Memory/_digest.md
#
# WHAT IT IS
#   A small (<= ~8 KB) file every AI runtime @imports (Claude Code / Codex / Gemini).
#   = curated core facts (_core-memory.md body) + headline recent patterns / failures /
#   sessions pulled from the _index/*.txt grep indexes (date-sorted).
#
# DESIGN
#   - Reads _core-memory.md verbatim (minus frontmatter + HTML comments) as the heart.
#   - Recent lists are one-liners derived from _index (regen-ai-memory-index.sh must run first
#     for freshest data; digest still works on stale index).
#   - Hard char budget (BUDGET) - trims recent lists if exceeded, never the core block.
#   - Idempotent; output carries a DO-NOT-EDIT header.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VAULT_ROOT="${1:-$(cd "$SCRIPT_DIR/.." && pwd)}"
AI_MEMORY="$VAULT_ROOT/Engineering/AI-Memory"
GENERATED_DATE="$(date '+%Y-%m-%d %H:%M:%S')"
BUDGET="${DIGEST_BUDGET:-8000}"   # max chars of recent-lists payload (core block always kept)

PYEOF_SCRIPT=$(cat <<'PYEOF'
import sys, os, re

ai_memory, generated_date, budget = sys.argv[1], sys.argv[2], int(sys.argv[3])
index_dir = os.path.join(ai_memory, '_index')

def read(path):
    try:
        with open(path, encoding='utf-8', errors='replace') as f:
            return f.read()
    except OSError:
        return ''

def core_body(text):
    """Strip frontmatter + HTML comments + collapse blank-only sections from _core-memory.md."""
    text = re.sub(r'^---\s*\n.*?\n---\s*\n', '', text, flags=re.DOTALL)   # frontmatter
    text = re.sub(r'<!--.*?-->', '', text, flags=re.DOTALL)              # html comments
    # Drop the leading H1 + its blockquote help (keep from first H2 onward)
    m = re.search(r'^##\s', text, flags=re.MULTILINE)
    if m:
        text = text[m.start():]
    # collapse 3+ blank lines
    text = re.sub(r'\n{3,}', '\n\n', text).strip()
    return text

def index_rows(name, date_col, label_cols, top):
    """Parse an _index file, sort by date col desc, return top N formatted one-liners."""
    raw = read(os.path.join(index_dir, name))
    rows = []
    for line in raw.splitlines():
        if not line or line.startswith('#'):
            continue
        parts = [p.strip() for p in line.split('|')]
        if len(parts) <= max(date_col, *label_cols):
            continue
        date = parts[date_col]
        label = ' · '.join(parts[c] for c in label_cols if c < len(parts))
        path = parts[-1]
        base = os.path.basename(path).removesuffix('.md')
        rows.append((date, label, base))
    rows.sort(key=lambda r: r[0], reverse=True)
    return [f"- {d} · {lbl} · `{base}`" for d, lbl, base in rows[:top]]

core = core_body(read(os.path.join(ai_memory, '_core-memory.md')))

# Recent headline lists (date-sorted desc). Column layout matches regen-ai-memory-index.sh.
recent_patterns = index_rows('patterns-by-domain.txt', date_col=1, label_cols=[0], top=8)
recent_failures = index_rows('failures-by-pattern.txt', date_col=3, label_cols=[1, 0], top=5)
recent_sessions = index_rows('sessions-by-agent.txt', date_col=2, label_cols=[1, 0], top=6)

header = (
    f"<!-- Generated by gen-memory-digest.sh on {generated_date}. DO NOT EDIT. "
    f"Source: _core-memory.md + _index/. -->\n"
    f"# AI-Memory Digest\n\n"
    f"> Always-load memory cho mọi AI runtime (@import). Core facts + headline recent. "
    f"Sâu hơn: grep `_index/*.txt` hoặc đọc `{{type}}/<domain>/`.\n"
)

def section(title, items):
    if not items:
        return ''
    return f"\n## {title}\n\n" + '\n'.join(items) + '\n'

recents = (
    section('Recent patterns', recent_patterns)
    + section('Recent failures (lessons)', recent_failures)
    + section('Recent sessions', recent_sessions)
)

# Budget guard: core always kept; trim recents from the tail if over budget.
while len(recents) > budget and recents:
    lines = recents.rstrip().split('\n')
    if len(lines) <= 1:
        break
    recents = '\n'.join(lines[:-1]) + '\n'

out = header + '\n' + core + '\n' + recents
sys.stdout.write(out)
PYEOF
)

OUT="$AI_MEMORY/_digest.md"
python3 - "$AI_MEMORY" "$GENERATED_DATE" "$BUDGET" <<< "$PYEOF_SCRIPT" > "$OUT"
CHARS=$(wc -c < "$OUT")
echo "[gen-memory-digest] wrote $OUT ($CHARS chars, budget recents=$BUDGET)"
